import { useEffect, useState } from 'react';
import type { useRaceWeekend } from '../hooks/useRaceWeekend';
import { raceTime } from '../utils/data';
type Props = { weekend: ReturnType<typeof useRaceWeekend>; timingError?: string; onTiming: () => void; onReplay: () => void };
export default function RaceWeekend({ weekend: w, timingError, onTiming, onReplay }: Props) {
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const id = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id); }, []);
  const race = w.race;
  if (!race) return <div className="weekend"><div className="race-card"><h2>{w.loading ? 'Finding the current race weekend…' : 'Weekend data unavailable'}</h2><p>{w.error || 'Loading the season calendar.'}</p><button onClick={w.refresh}>Retry</button></div></div>;
  const delta = raceTime(race) - now;
  const countdown = delta > 0 ? `${Math.floor(delta / 86400000)}d ${Math.floor(delta / 3600000) % 24}h ${Math.floor(delta / 60000) % 60}m ${Math.floor(delta / 1000) % 60}s` : 'Scheduled start has passed';
  const standings = w.standings?.StandingsLists[0];
  const weather = w.weather?.current;
  const sessions = ['FirstPractice','SecondPractice','ThirdPractice','SprintQualifying','Sprint','Qualifying'].flatMap(key => { const s = race[key] as {date:string;time?:string} | undefined; return s?.date ? [{ key: key.replace(/([a-z])([A-Z])/g, '$1 $2'), date: `${s.date}T${s.time || '12:00:00Z'}` }] : []; });
  sessions.push({ key: 'Grand Prix', date: `${race.date}T${race.time || '12:00:00Z'}` });
  return <div className="weekend">
    <div className="weekend-hero"><div><p className="eyebrow">RACE WEEKEND / {race.season} / ROUND {race.round}</p><h1>{race.raceName}</h1><p className="venue">{race.Circuit.circuitName} · {race.Circuit.Location.country}</p><div className="weekend-actions"><button className="primary-action" onClick={onTiming}>Open timing cockpit ↗</button><button onClick={onReplay}>Replay a past race</button><a href="https://www.formula1.com/en/live-timing" target="_blank" rel="noreferrer">Official live timing ↗</a></div></div><div className="countdown"><span>{delta > 0 ? 'LIGHTS OUT IN' : 'RACE DAY'}</span><strong>{countdown}</strong><p>{new Date(raceTime(race)).toLocaleString(undefined, { weekday:'long', month:'short', day:'numeric', hour:'numeric', minute:'2-digit', timeZoneName:'short' })}</p><small>Scheduled time; delays require confirmation from race control.</small></div></div>
    {(timingError || w.error) && <div className="feed-notice" role="status"><strong>{timingError ? 'Timing feed unavailable' : 'Weekend refresh failed'}</strong><p>{timingError || w.error}</p>{w.error && <p>Previously fetched weekend data is retained below.</p>}</div>}
    <div className="weekend-grid"><section className="race-card"><div className="card-heading"><h2>Conditions near the circuit</h2><span>MODEL ESTIMATE</span></div>{weather ? <><div className="weather-metrics"><div><strong>{weather.temperature_2m}°</strong><span>Air · °C</span></div><div><strong>{weather.relative_humidity_2m}%</strong><span>Humidity</span></div><div><strong>{weather.wind_speed_10m}</strong><span>Wind · km/h</span></div><div><strong>{weather.precipitation}</strong><span>Precipitation · mm</span></div></div><p className="fine-print">Open-Meteo · {new Date(weather.time+'Z').toLocaleString()} · Regional model data, not measured track temperature or race-control conditions.</p></> : <p>Weather is temporarily unavailable.</p>}</section>
    <section className="race-card"><div className="card-heading"><h2>Weekend schedule</h2><span>YOUR LOCAL TIME</span></div><div className="session-list">{sessions.map(s => <div key={s.key} className={s.key === 'Grand Prix' ? 'race-session' : ''}><span>{s.key}</span><time dateTime={s.date}>{new Date(s.date).toLocaleString(undefined,{weekday:'short', hour:'numeric',minute:'2-digit'})}</time></div>)}</div></section>
    <section className="race-card"><div className="card-heading"><h2>Qualifying classification</h2><span>PRE-RACE</span></div><p className="fine-print">Qualifying order; grid penalties and pit-lane starts may change the final starting grid.</p>{w.qualifying.length ? <div className="table-scroll"><table><thead><tr><th>Pos</th><th>Driver / team</th><th>Best segment</th></tr></thead><tbody>{w.qualifying.map(r => <tr key={r.Driver.driverId}><td>{r.position}</td><td><strong>{r.Driver.givenName} {r.Driver.familyName}</strong><small>{r.Constructor.name}</small></td><td className="mono">{r.Q3 || r.Q2 || r.Q1 || '—'}</td></tr>)}</tbody></table></div> : <p className="empty-note">Qualifying results have not been published by the data provider yet.</p>}</section>
    <section className="race-card"><div className="card-heading"><h2>Championship standings</h2><span>AFTER ROUND {standings?.round || '—'}</span></div>{standings?.DriverStandings?.length ? <div className="table-scroll"><table><thead><tr><th>Pos</th><th>Driver / team</th><th>Points</th></tr></thead><tbody>{standings.DriverStandings.map(r => <tr key={r.Driver.driverId}><td>{r.position}</td><td><strong>{r.Driver.givenName} {r.Driver.familyName}</strong><small>{r.Constructors.map(c => c.name).join(' / ')}</small></td><td className="mono">{r.points}</td></tr>)}</tbody></table></div> : <p className="empty-note">Standings are temporarily unavailable.</p>}</section></div>
    <div className="weekend-footer"><p>Calendar, qualifying & standings: Jolpica-F1 · {w.updated ? `Checked ${w.updated.toLocaleTimeString()}` : 'Loading'} · Refreshes every 5 minutes</p><button onClick={w.refresh}>Refresh weekend</button></div>{w.warnings.map(s => <p key={s} className="fine-print">{s}</p>)}
  </div>;
}
